### ISSUE TITLE
Add Support for Predefined Global Variables

### ISSUE THREAD

**Issue by beckje01** [millerjam/grails-jslint#3]
We need to support predefined globals such as $ for jQuery

**Comment by bendavieshe3** [comment]
I don't get warnings about this in JsLint - is it for a specific option? On the other hand since I have been testing the plugin most of my markup is in self-executing functions where jQuery (aka $ the global) is passed in. This could be masking the issue from me. 

Someone else must have had this problem as well surely?

**Comment by beckje01** [comment]
It is supported by jslint4java I just need to add the param to pass it to the ant task as it works differently from the other options.

**Comment by c089** [comment]
could you publish a -snapshot version of the plugin? I packaged one myself from a git clone but can't find a simple way to have that available for all our devs.

**Comment by beckje01** [comment]
@c089 I went ahead and moved the final feature that was holding up release to the next version so I pushed out v0.5 you should now be able to get it from grails.org/plugins

**Comment by c089** [comment]
thanks :)
